name: Build and Push Docker Images

on:
  push:
    branches: [main, beta]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and push to Docker Hub
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build craftcms/demo-happylager:latest
        uses: docker/build-push-action@v2
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: craftcms/demo-happylager:latest

      - name: Build craftcms/demo-happylager:beta
        uses: docker/build-push-action@v2
        if: ${{ github.ref == 'refs/heads/beta' }}
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: craftcms/demo-happylager:beta
